export PATH="$PATH:$HOME/.cabal/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.ghcup/bin"
export PATH="$PATH:$HOME/perl5/bin"
export PATH="$PATH:$HOME/.idris2/bin"
export PATH="$PATH:$HOME/Install/ghc9/bin"
